#!/bin/bash
# This script resets shared by copying it from teamcast-backend service
# Source and destination paths
BACKEND_DIR="../teamcast-backend/src"
CURRENT_DIR="src/lib/shared"

set -e

echo "Starting shared reset process..."

# Remove existing shared directory if it exists
if [ -d "${CURRENT_DIR}" ]; then
  echo "Removing existing shared directory..."
  rm -rf "${CURRENT_DIR}"
else
  echo "Shared directory does not exist, skipping removal."
fi

# Create shared directory
mkdir -p "${CURRENT_DIR}"

# Check if source shared directory exists before copying
if [ ! -d "${BACKEND_DIR}/shared" ]; then
  echo "Error: Source shared directory not found at ${BACKEND_DIR}/shared"
  exit 1
fi

echo "Copying shared folder from backend service..."
cp -r "${BACKEND_DIR}/shared/." "${CURRENT_DIR}"

echo "Regenerating index.ts file..."
# Create the index.ts file
INDEX_FILE="${CURRENT_DIR}/index.ts"

# Start with empty file
echo "// This file is auto-generated by reset-shared.sh" > $INDEX_FILE
echo "// Last generated: $(date)" >> $INDEX_FILE
echo "// Only TypeScript (.ts) files are included" >> $INDEX_FILE

# Find all first-level directories in shared
for dir in $(find "${CURRENT_DIR}" -maxdepth 1 -type d | sort | grep -v "^${CURRENT_DIR}$"); do
  dir_name=$(basename "$dir")
  
  # Check if directory contains any TypeScript files
  if [ $(find "${CURRENT_DIR}/${dir_name}" -name "*.ts" | wc -l) -gt 0 ]; then
    echo -e "\n// Export from ${dir_name}" >> $INDEX_FILE
    
    # Find all TypeScript files in this directory and its subdirectories
    find "${CURRENT_DIR}/${dir_name}" -name "*.ts" -not -path "*/node_modules/*" | sort | while read -r file; do
      rel_path=$(echo "$file" | sed "s|${CURRENT_DIR}/||")
      # Remove the .ts extension from the import path
      import_path=$(echo "$rel_path" | sed 's/\.ts$//')
      echo "export * from './${import_path}';" >> $INDEX_FILE
    done
  fi
done

# Handle any TypeScript files directly in shared (excluding index.ts itself)
if [ $(find "${CURRENT_DIR}" -maxdepth 1 -name "*.ts" ! -name "index.ts" | wc -l) -gt 0 ]; then
  echo -e "\n// Export files from root directory" >> $INDEX_FILE
  find "${CURRENT_DIR}" -maxdepth 1 -name "*.ts" ! -name "index.ts" | sort | while read -r file; do
    file_name=$(basename "$file")
    # Remove the .ts extension from the import path
    import_name=$(echo "$file_name" | sed 's/\.ts$//')
    echo "export * from './${import_name}';" >> $INDEX_FILE
  done
fi

# Remove all @singleton decorators from shared code
echo "Removing @singleton decorators from shared code..."
FILES_TO_FIX=$(grep -l "@singleton" $(find "${CURRENT_DIR}" -name "*.ts") 2>/dev/null || true)
if [ ! -z "$FILES_TO_FIX" ]; then
  for file in $FILES_TO_FIX; do
    # Use different sed syntax for macOS compatibility
    if [[ "$OSTYPE" == "darwin"* ]]; then
      sed -i '' '/@singleton/d' "$file"
    else
      sed -i '/@singleton/d' "$file"
    fi
  done
  echo "Removed @singleton decorators from $(echo "$FILES_TO_FIX" | wc -l | tr -d ' ') files."
else
  echo "No @singleton decorators found."
fi

# Remove all unused singleton imports from shared code
echo "Removing unused singleton imports from shared code..."
FILES_TO_FIX=$(grep -l "import.*singleton.*from.*decorators" $(find "${CURRENT_DIR}" -name "*.ts") 2>/dev/null || true)
if [ ! -z "$FILES_TO_FIX" ]; then
  for file in $FILES_TO_FIX; do
    # Use different sed syntax for macOS compatibility
    if [[ "$OSTYPE" == "darwin"* ]]; then
      sed -i '' '/import.*singleton.*from.*decorators/d' "$file"
    else
      sed -i '/import.*singleton.*from.*decorators/d' "$file"
    fi
  done
  echo "Removed unused singleton imports from $(echo "$FILES_TO_FIX" | wc -l | tr -d ' ') files."
else
  echo "No unused singleton imports found."
fi

# Check if download-api-docs script exists and run it
if grep -q "download-api-docs" package.json; then
    echo "Downloading API docs..."
    npm run download-api-docs
    if [ $? -ne 0 ]; then
        echo "Error: Failed to download API docs"
        exit 1
    fi
else
    echo "Warning: download-api-docs script not found in package.json, skipping..."
fi

echo "Shared reset completed successfully!"
echo "Shared folder is now available at @/lib/shared (src/shared)"